"""Adapter ABC.

Each tool adapter renders the parsed canonical SKILL.md into the file the
host tool expects. Adapters are pure: same canonical input + same context
must produce byte-identical output (drives idempotency + drift detection).
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path


@dataclass
class ParsedCanonical:
    """Result of splitting the canonical SKILL.md into tool-conditional blocks.

    common: text outside any TOOL: block (kept for every tool).
    blocks: list of (kind, names, content, anchor) tuples in source order.
        - kind: "only" | "except" | "override"
        - names: tool names the block applies to (set)
        - content: raw text inside the block
        - anchor: for "override", the preceding paragraph it replaces; else None
    raw: original unparsed text (for sha256 stamping).
    """
    common: str
    blocks: list[tuple]
    raw: str


@dataclass
class RenderContext:
    """Inputs to placeholder substitution + per-tool transforms."""
    tool: str
    tool_display: str
    invocation_hint: str
    max_concept_tokens: int = 1500
    manifest_token_cap: int = 3000
    canonical_sha256: str = ""
    skill_version: str = "v2"


class Adapter(ABC):
    """Base class for all tool adapters."""

    name: str                       # registry key, e.g. "claude"
    display: str                    # human-readable, e.g. "Claude Code"
    output_path_rel: str            # relative to repo root
    convention_version: str         # YYYY-MM spec version targeted
    merge_mode: str = "replace"     # "replace" or "sentinel"
    critical_banner: str | None = None  # prepended for terse-LLM tools
    incorporates_banner: bool = False
    """When True, the adapter's transform() places the banner itself;
    emit-adapters MUST NOT prepend it again. Used by tools that have
    leading frontmatter (Cursor's .mdc) where the banner can't be first."""

    def output_path(self, repo_root: Path) -> Path:
        return repo_root / self.output_path_rel

    def trailing_stamp(self, ctx: RenderContext) -> str:
        return (
            f"\n\n<!-- generated by repokb emit-adapters@{ctx.skill_version} "
            f"from SKILL.md@{ctx.canonical_sha256[:12]}\n"
            f"     adapter: {self.name} CONVENTION_VERSION={self.convention_version}; "
            f"do not edit -->\n"
        )

    @abstractmethod
    def transform(self, parsed: ParsedCanonical, ctx: RenderContext) -> str:
        """Render the parsed canonical into the tool-native instruction body.

        Must NOT include the trailing stamp — emit-adapters appends that.
        Must NOT touch disk — pure string in, pure string out.
        """
        raise NotImplementedError

    def make_context(self, canonical_sha256: str) -> RenderContext:
        """Default per-adapter context. Override to tweak budgets per tool."""
        return RenderContext(
            tool=self.name,
            tool_display=self.display,
            invocation_hint=self._default_invocation_hint(),
            canonical_sha256=canonical_sha256,
        )

    def _default_invocation_hint(self) -> str:
        return f"When working in this repository, follow the protocol below."


SENTINEL_START = "<!-- repokb:start version=\"2\" -->"
SENTINEL_END = "<!-- repokb:end -->"
